/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `application`
    `org.openjfx.javafxplugin`
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation "org.openjfx:javafx-controls:17"
    implementation "org.openjfx:javafx-fxml:17"
}

group = "ch.autumo.games"
version = "2.0"
description = "ShootVitor"
java.sourceCompatibility = JavaVersion.VERSION_1_8

application {                                                           
    mainClass = "ch.autumo.games.shootvitor.App"
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
